### ISSUE TITLE
Usage of boundary samples in OOD generator

### ISSUE THREAD

**Issue by laymond1** [jpmorganchase/ovor#5]
Hello, Thank you for sharing your impressive research and results!

While reading your paper and analyzing the code, I'm not sure I understand how the ood generator code works. In the paper, it is mentioned that the selected boundary samples are used to generate virtual outliers. However, in the code, it seems that boundary_points is not utilized.

Could you please clarify this part?
Thank you in advance!

```
    def _generate(self, in_dist, num_cls):
        offsets = self.dis.rsample((self.sample_from,))
        normed = in_dist / torch.norm(in_dist, p=2, dim=1, keepdim=True)
        select = min(self.select, normed.shape[0])
        rand_ind = np.random.choice(normed.shape[0], replace=False)
        self.knn_idx.add(normed.numpy())
        boundary_ids = self._boundary(normed, select)
        boundary_points = torch.cat([in_dist[i:i+1].repeat(self.sample_from, 1) for i in boundary_ids])
        ood_list = self.cov_mat * offsets.repeat(select, 1)
        oods = self._select_ood(ood_list, num_cls)
        self.knn_idx.reset()
        return oods
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the _generate method in the NPOS class to utilize boundary points for generating virtual outliers, as described in the paper. This change ensures that the selected boundary samples are used in the OOD generation process.

You can review changes in this commit: https://github.com/mnmnk43434/jpmorganchase-ovor-5/commit/49f608d7b4b380b7c61fc7d463c1af57296227b1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by laymond1** [comment]
Thank you for your quick response!

Your clarification greatly helped me understand the implementation.

Thank you again for addressing my question!
